// Generated by gencpp from file hugs_control/HugsData.msg
// DO NOT EDIT!


#ifndef HUGS_CONTROL_MESSAGE_HUGSDATA_H
#define HUGS_CONTROL_MESSAGE_HUGSDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hugs_control
{
template <class ContainerAllocator>
struct HugsData_
{
  typedef HugsData_<ContainerAllocator> Type;

  HugsData_()
    : data()  {
    }
  HugsData_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::hugs_control::HugsData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hugs_control::HugsData_<ContainerAllocator> const> ConstPtr;

}; // struct HugsData_

typedef ::hugs_control::HugsData_<std::allocator<void> > HugsData;

typedef boost::shared_ptr< ::hugs_control::HugsData > HugsDataPtr;
typedef boost::shared_ptr< ::hugs_control::HugsData const> HugsDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hugs_control::HugsData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hugs_control::HugsData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hugs_control::HugsData_<ContainerAllocator1> & lhs, const ::hugs_control::HugsData_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hugs_control::HugsData_<ContainerAllocator1> & lhs, const ::hugs_control::HugsData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hugs_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hugs_control::HugsData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hugs_control::HugsData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hugs_control::HugsData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hugs_control::HugsData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hugs_control::HugsData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hugs_control::HugsData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hugs_control::HugsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f43a8e1b362b75baa741461b46adc7e0";
  }

  static const char* value(const ::hugs_control::HugsData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf43a8e1b362b75baULL;
  static const uint64_t static_value2 = 0xa741461b46adc7e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::hugs_control::HugsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hugs_control/HugsData";
  }

  static const char* value(const ::hugs_control::HugsData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hugs_control::HugsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] data  # Array of bytes representing the data buffer\n"
"\n"
;
  }

  static const char* value(const ::hugs_control::HugsData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hugs_control::HugsData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HugsData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hugs_control::HugsData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hugs_control::HugsData_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUGS_CONTROL_MESSAGE_HUGSDATA_H
